keys:
  - &framework age1f0uj3tdh2nrpjgtjflmyrlw4mw8k2jjgx8dn8ksype304jkujavq8vnx96
  - &github_ssh_key age1qr4tv5ap8825g00vvctk43zwrc25s0alxeuuyxe7ureg82paw5ysgprarm
#  - &server_batchn age1wnwfnrqhewjh39pmtyc8zhqw606znskt4h5p9s3pve4apd67gapqj6tr0k
# …more server keys go here…
creation_rules:
  - path_regex: secrets/keys/git/[^/]+\.(yaml|json|env|ini|txt)$
    key_groups:
    - age:
      - *framework
  - path_regex: secrets/keys/vpn/[^/]+\.(yaml|json|env|ini|txt)$
    unencrypted_regex: ^(Address|DNS|AllowedIPs)$
    key_groups:
    - age:
      - *framework
    
