keys:
  - &github_ssh_key age1qr4tv5ap8825g00vvctk43zwrc25s0alxeuuyxe7ureg82paw5ysgprarm
#  - &server_batchn age1wnwfnrqhewjh39pmtyc8zhqw606znskt4h5p9s3pve4apd67gapqj6tr0k
# …more server keys go here…
creation_rules:
  - path_regex: framework/secrets/keys/git/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *github_ssh_key
