# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # === KERNEL MODULES ===
  boot.initrd.availableKernelModules = [
    # Common modules from both configs
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "uas"
  ] ++ (lib.mkIf config.nixpkgs.hostPlatform.isIntel [
    # Intel-specific modules 
    "usbhid"
    "i915"
    "iwlwifi"
  ]) ++ (lib.mkIf config.nixpkgs.hostPlatform.isAmd [
    # AMD-specific modules 
    "sd_mod"
  ]);

  boot.initrd.kernelModules = [ ];

  # Set KVM module based on CPU
  boot.kernelModules =
    if config.nixpkgs.hostPlatform.isIntel then [ "kvm-intel" ]
    else if config.nixpkgs.hostPlatform.isAmd then [ "kvm-amd" ]
    else [ ];

  boot.extraModulePackages = [ ];

  # Add AMD-specific modprobe config only on the AMD machine 
  boot.extraModprobeConfig = lib.mkIf config.nixpkgs.hostPlatform.isAmd ''
    options mt7925e disable_aspm=1 disable_ps=1 fwlog_en=0
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/46d48710-36ca-47d1-b5b0-b77e5b6c73d9";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F2D4-E2BE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/75484b84-26e8-4c40-94f9-e36726e4488f";
      fsType = "btrfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkIf config.nixpkgs.hostPlatform.isIntel (lib.mkDefault config.hardware.enableRedistributableFirmware);
  hardware.cpu.amd.updateMicrocode = lib.mkIf config.nixpkgs.hostPlatform.isAmd (lib.mkDefault config.hardware.enableRedistributableFirmware);
}